name: Build Android Bundle
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Process for GSons
        run: |
          # 1. Folder ke andar dakhil hona
          cd "Al-Mumin-Guide__"
          
          # 2. Files check karna (taake machine ko pata ho rasta sahi hai)
          ls
          
          # 3. Missing files khud banana
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android
          
          # 4. Capacitor setup
          npx cap init "Al Mumin Guide" com.gsons.mumin --web-dir .
          npx cap add android || true
          npx cap sync android
          
          # 5. Final Android Build
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Upload .aab Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "**/app-release.aab"
