name: Build Android Bundle
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup and Build
        run: |
          # 1. Folder check karna
          ls -R
          
          # 2. Capacitor install karna (Global level par)
          npm install -g @capacitor/cli
          
          # 3. Folder ke andar ja kar kaam shuru karna
          cd "Al-Mumin-Guide__"
          
          # 4. Zaroori files install karna
          npm install @capacitor/core @capacitor/android
          
          # 5. Android project initialize karna
          npx cap init "Al Mumin Guide" com.gsons.mumin --web-dir .
          npx cap add android || true
          npx cap sync android
          
          # 6. Bundle (.aab) banana
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Upload .aab Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "**/app-release.aab"
